use super::types::*;
use serde_json::{json, Value};

/// Returns a static vector of all foundational capabilities baked
/// into the Ordo Daemon. This encompasses every capability from system status
/// to deep LLM invocations and database access.
pub fn built_in_capabilities() -> Vec<CapabilityDefinition> {
    vec![
        capability(
            "capability.catalog.list",
            "List Capability Catalog",
            "Read the governed capabilities registered in this appliance.",
            "system",
            json!({ "type": "object", "additionalProperties": false }),
            json!({ "type": "object", "properties": { "capabilities": { "type": "array" } } }),
            "rust",
            true,
            MCP_EXPORT_POLICY_READ_ONLY,
            false,
            &[],
        ),
        capability(
            "system.status.read",
            "Read System Status",
            "Read daemon health, readiness, and catalog status.",
            "system",
            json!({ "type": "object", "additionalProperties": false }),
            json!({ "type": "object", "properties": { "health": { "type": "object" }, "readiness": { "type": "object" } } }),
            "rust",
            true,
            MCP_EXPORT_POLICY_READ_ONLY,
            false,
            &[],
        ),
        capability(
            "appliance.runtime.status",
            "Read Appliance Runtime Status",
            "Read the local appliance runtime status exposed by the daemon.",
            "system",
            json!({ "type": "object", "additionalProperties": false }),
            json!({ "type": "object" }),
            "rust",
            true,
            MCP_EXPORT_POLICY_READ_ONLY,
            false,
            &[],
        ),
        capability(
            "install.state.read",
            "Read Local Install State",
            "Read local appliance install state, owner profile, business profile, and provider readiness summary.",
            "install",
            json!({ "type": "object", "additionalProperties": false }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &[],
        ),
        capability(
            "install.complete",
            "Complete Local Install",
            "Persist local owner and business install identity for the appliance.",
            "install",
            json!({ "type": "object", "additionalProperties": true }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &[],
        ),
        capability(
            "local_session.login",
            "Create Local Session Login",
            "Create or restore a local appliance browser session from local login input.",
            "install",
            json!({ "type": "object", "additionalProperties": true }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &["local_session"],
        ),
        capability(
            "local_session.register",
            "Create Local Session Registration",
            "Create or restore a local appliance browser session from local registration input.",
            "install",
            json!({ "type": "object", "additionalProperties": true }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &["local_session"],
        ),
        capability(
            "providers.list",
            "List Provider Configuration",
            "Read redacted local provider configuration and secret source state.",
            "providers",
            json!({ "type": "object", "additionalProperties": false }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &[],
        ),
        capability(
            "providers.update",
            "Update Provider Configuration",
            "Update local provider configuration and write-only provider secret references.",
            "providers",
            json!({ "type": "object", "additionalProperties": true }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &[],
        ),
        capability(
            "business.facts.list",
            "List Business Facts",
            "Read local business facts through visibility and publication filters.",
            "business",
            json!({ "type": "object", "additionalProperties": true }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &[],
        ),
        capability(
            "business.facts.write",
            "Write Business Facts",
            "Create or update local business facts with provenance, visibility, and publication state.",
            "business",
            json!({ "type": "object", "additionalProperties": true }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &[],
        ),
        capability(
            "corpus.sources.list",
            "List Corpus Sources",
            "Read governed corpus source records through local protected daemon routes.",
            "corpus",
            json!({ "type": "object", "additionalProperties": true }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &["corpus.source"],
        ),
        capability(
            "corpus.sources.write",
            "Write Corpus Sources",
            "Create or update governed corpus sources with provenance and classification metadata.",
            "corpus",
            json!({ "type": "object", "additionalProperties": true }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &["corpus.source"],
        ),
        capability(
            "corpus.items.list",
            "List Corpus Items",
            "Read governed corpus items through visibility and resource access filters.",
            "corpus",
            json!({ "type": "object", "additionalProperties": true }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &["corpus.item"],
        ),
        capability(
            "corpus.items.write",
            "Write Corpus Items",
            "Create or update governed corpus items and maintain the local SQLite FTS index.",
            "corpus",
            json!({ "type": "object", "additionalProperties": true }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &["corpus.item"],
        ),
        capability(
            "corpus.retrieve",
            "Retrieve Corpus Evidence",
            "Run governed local SQLite FTS retrieval with approval, visibility, and access filtering.",
            "corpus",
            json!({ "type": "object", "required": ["query"], "additionalProperties": true }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &["corpus.retrieval"],
        ),
        capability(
            "answer.drafts.list",
            "List Answer Drafts",
            "Read durable answer draft records and their cited corpus evidence through protected daemon routes.",
            "answers",
            json!({ "type": "object", "additionalProperties": false }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &["answer.draft"],
        ),
        capability(
            "answer.drafts.prepare",
            "Prepare Evidence-Backed Answer Draft",
            "Create a local answer draft scaffold only after governed corpus retrieval records source evidence.",
            "answers",
            json!({ "type": "object", "required": ["question"], "additionalProperties": true }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &["answer.draft", "corpus.retrieval"],
        ),
        capability(
            "mcp.packs.list",
            "List MCP Packs",
            "Read local MCP pack manifests, tool metadata, export state, and provenance through protected daemon routes.",
            "mcp",
            json!({ "type": "object", "additionalProperties": false }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &["mcp.pack"],
        ),
        capability(
            "mcp.packs.write",
            "Write MCP Packs",
            "Validate, install, update, or disable local MCP pack metadata without adding arbitrary code execution.",
            "mcp",
            json!({ "type": "object", "additionalProperties": true }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &["mcp.pack"],
        ),
        capability(
            "entry_points.list",
            "List Tracked Entry Points",
            "Read tracked entry points and their public-safe destination payloads.",
            "entry_points",
            json!({ "type": "object", "additionalProperties": false }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &[],
        ),
        capability(
            "entry_points.write",
            "Write Tracked Entry Points",
            "Create or update tracked links and QR payload records for public-safe destinations.",
            "entry_points",
            json!({ "type": "object", "additionalProperties": true }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &[],
        ),
        capability(
            "visitor_sessions.list",
            "List Visitor Sessions",
            "Read visitor sessions with tracked entry point attribution context.",
            "entry_points",
            json!({ "type": "object", "additionalProperties": false }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &[],
        ),
        capability(
            "offers.list",
            "List Offers",
            "Read durable offer records and their publication state.",
            "offers",
            json!({ "type": "object", "additionalProperties": false }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &[],
        ),
        capability(
            "offers.write",
            "Write Offers",
            "Create or update durable offer records and public availability state.",
            "offers",
            json!({ "type": "object", "additionalProperties": true }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &[],
        ),
        capability(
            "offer_builder.inspect",
            "Inspect Offer Builder",
            "Read owner/admin offer-builder readiness, supported references, and explicit deferrals.",
            "offers",
            json!({ "type": "object", "additionalProperties": false }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &[],
        ),
        capability(
            "offer_builder.write",
            "Write Offer Builder",
            "Create, edit, and publish pilot offers only after supported reference and public-safety validation.",
            "offers",
            json!({ "type": "object", "additionalProperties": true }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &["offer", "hosted_trial", "tracked_entry_point"],
        ),
        capability(
            "offer_acceptances.list",
            "List Offer Acceptances",
            "Read offer acceptances with visitor session and attribution context.",
            "offers",
            json!({ "type": "object", "additionalProperties": false }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &[],
        ),
        capability(
            "trials.list",
            "List Trials",
            "Read trial lifecycle state and recorded decision evidence.",
            "offers",
            json!({ "type": "object", "additionalProperties": false }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &[],
        ),
        capability(
            "trials.transition",
            "Transition Trial State",
            "Record conversion, void, expiration, or follow-up-needed trial decisions.",
            "offers",
            json!({ "type": "object", "additionalProperties": true }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &[],
        ),
        capability(
            "hosted_trials.capacity.inspect",
            "Inspect Hosted Trial Capacity",
            "Read hosted trial capacity, active slots, waitlist, expiration, backup, and reset guard state.",
            "system",
            json!({ "type": "object", "additionalProperties": false }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &[],
        ),
        capability(
            "hosted_trials.reset_ready.validate",
            "Validate Hosted Trial Reset Readiness",
            "Record owner-reviewed hosted trial reset readiness after expiration and backup/export evidence.",
            "system",
            json!({
                "type": "object",
                "required": ["trialId", "backupEvidenceRefs", "ownerDecision"],
                "properties": {
                    "trialId": { "type": "string" },
                    "backupEvidenceRefs": { "type": "array", "items": { "type": "string" } },
                    "ownerDecision": { "type": "object" }
                },
                "additionalProperties": false
            }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &[],
        ),
        capability(
            "surface.work_items.list",
            "List Surface Work Items",
            "Refresh and read the local CQRS-lite work item projection for product surfaces.",
            "surface",
            json!({
                "type": "object",
                "properties": {
                    "viewer": {
                        "type": "string",
                        "enum": ["public", "member", "staff", "owner", "system"]
                    },
                    "surfaceKind": { "type": "string" },
                    "roomKind": { "type": "string" },
                    "actorId": { "type": "string" },
                    "connectionId": { "type": "string" },
                    "limit": { "type": "integer", "minimum": 0, "maximum": 500 }
                },
                "additionalProperties": false
            }),
            json!({
                "type": "object",
                "properties": {
                    "items": { "type": "array" }
                }
            }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &["surface.work_item"],
        ),
        capability(
            "connections.list",
            "List Connections",
            "Read durable connection records and status state.",
            "connections",
            json!({ "type": "object", "additionalProperties": false }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &[],
        ),
        capability(
            "connections.write",
            "Write Connections",
            "Create and update durable connection records and lifecycle state.",
            "connections",
            json!({ "type": "object", "additionalProperties": true }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &[],
        ),
        capability(
            "connection_grants.write",
            "Write Connection Grants",
            "Create and revoke explicit scoped grants attached to connections.",
            "connections",
            json!({ "type": "object", "additionalProperties": true }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &[],
        ),
        capability(
            "connection_grants.list",
            "List Connection Grants",
            "Read explicit scoped grants attached to connections.",
            "connections",
            json!({ "type": "object", "additionalProperties": false }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &[],
        ),
        capability(
            "connection_events.list",
            "List Connection Events",
            "Read durable connection events and local receipt evidence.",
            "connections",
            json!({ "type": "object", "additionalProperties": false }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &[],
        ),
        capability(
            "availability.read",
            "Read Availability State",
            "Read local availability schedule and operator presence state.",
            "availability",
            json!({ "type": "object", "additionalProperties": false }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &[],
        ),
        capability(
            "availability.write",
            "Write Availability State",
            "Update local availability schedule and operator presence state.",
            "availability",
            json!({ "type": "object", "additionalProperties": true }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &[],
        ),
        capability(
            "handoff.eligibility.evaluate",
            "Evaluate Handoff Eligibility",
            "Record a local handoff eligibility decision with evidence.",
            "handoff",
            json!({ "type": "object", "additionalProperties": true }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &[],
        ),
        capability(
            "handoff.inbox.list",
            "List Handoff Inbox",
            "Read owner attention inbox items and local handoff state.",
            "handoff",
            json!({ "type": "object", "additionalProperties": false }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &[],
        ),
        capability(
            "handoff.inbox.write",
            "Write Handoff Inbox",
            "Create and resolve owner attention inbox items without external delivery.",
            "handoff",
            json!({ "type": "object", "additionalProperties": true }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &[],
        ),
        capability(
            "handoff.receipts.list",
            "List Handoff Receipts",
            "Read local receipt evidence for handoff inbox items.",
            "handoff",
            json!({ "type": "object", "additionalProperties": false }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &[],
        ),
        capability(
            "conversation.read",
            "Read Conversations",
            "Read authorized conversation summaries, episodes, handoffs, and queue projections.",
            "conversation",
            json!({ "type": "object", "additionalProperties": true }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &["conversation"],
        ),
        capability(
            "conversation.bootstrap",
            "Bootstrap Member Conversation",
            "Create or restore local member conversation identities for the browser conversation gateway.",
            "conversation",
            json!({ "type": "object", "required": ["sessionId", "actorId"], "additionalProperties": false }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &["conversation", "local_session"],
        ),
        capability(
            "conversation.handoff.manage",
            "Manage Conversation Handoffs",
            "Create and transition governed conversation handoff objects with evidence.",
            "conversation",
            json!({ "type": "object", "additionalProperties": true }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &["conversation.handoff"],
        ),
        capability(
            "conversation.agent.delegate",
            "Delegate Conversation Agent",
            "Manage scoped Ordo delegation and public-posting mode for human-led conversations.",
            "conversation",
            json!({ "type": "object", "additionalProperties": true }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &["conversation.mode"],
        ),
        capability(
            "conversation.episode.manage",
            "Manage Conversation Episodes",
            "Create and review evidence-backed internal episode candidates below a relationship conversation.",
            "conversation",
            json!({ "type": "object", "additionalProperties": true }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &["conversation.segment"],
        ),
        capability(
            "conversation.message.create",
            "Create Conversation Message",
            "Submit a durable conversation message through the governed conversation protocol.",
            "conversation",
            json!({ "type": "object", "required": ["conversationId", "bodyMarkdown"], "additionalProperties": true }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &["conversation.message"],
        ),
        capability(
            "conversation.message.edit",
            "Edit Conversation Message",
            "Create a durable message revision without hiding prior message history.",
            "conversation",
            json!({ "type": "object", "required": ["messageId", "bodyMarkdown"], "additionalProperties": true }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &["conversation.message"],
        ),
        capability(
            "conversation.message.delete",
            "Delete Or Undo Conversation Message",
            "Record governed message tombstone or bounded undo state.",
            "conversation",
            json!({ "type": "object", "required": ["messageId"], "additionalProperties": true }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &["conversation.message"],
        ),
        capability(
            "conversation.reaction.write",
            "Write Conversation Reaction",
            "Add or remove durable conversation message reactions.",
            "conversation",
            json!({ "type": "object", "required": ["messageId", "reactionKey"], "additionalProperties": true }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &["conversation.reaction"],
        ),
        capability(
            "conversation.receipt.write",
            "Write Conversation Receipt",
            "Record delivered, displayed, read, and unread conversation receipt evidence.",
            "conversation",
            json!({ "type": "object", "required": ["conversationId"], "additionalProperties": true }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &["conversation.receipt"],
        ),
        capability(
            "conversation.presence.write",
            "Write Conversation Presence",
            "Update conversation typing, viewing, and presence snapshots.",
            "conversation",
            json!({ "type": "object", "required": ["conversationId"], "additionalProperties": true }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &["conversation.presence"],
        ),
        capability(
            "llm.invoke",
            "Invoke LLM Gateway",
            "Run a daemon-mediated, policy-aware provider request for a conversation.",
            "llm",
            json!({ "type": "object", "required": ["conversationId", "providerId", "modelId"], "additionalProperties": true }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &["llm.run", "conversation.message"],
        ),
        capability(
            "llm.cancel",
            "Cancel LLM Run",
            "Cancel an in-flight daemon-mediated LLM provider request.",
            "llm",
            json!({ "type": "object", "required": ["runId"], "additionalProperties": true }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &["llm.run"],
        ),
        capability(
            "llm.tool.request",
            "Request LLM Tool",
            "Record an inspectable tool request from a conversation LLM run.",
            "llm",
            json!({ "type": "object", "required": ["runId", "conversationId", "requestedCapabilityId"], "additionalProperties": true }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &["llm.tool_request"],
        ),
        capability(
            "llm.tool.approve",
            "Approve LLM Tool",
            "Approve a pending conversation LLM tool request with policy evidence.",
            "llm",
            json!({ "type": "object", "required": ["toolRequestId"], "additionalProperties": true }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &["llm.tool_request"],
        ),
        capability(
            "llm.tool.reject",
            "Reject LLM Tool",
            "Reject a pending conversation LLM tool request with policy evidence.",
            "llm",
            json!({ "type": "object", "required": ["toolRequestId", "reason"], "additionalProperties": true }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &["llm.tool_request"],
        ),
        capability(
            "llm.tool.execute",
            "Execute Approved LLM Tool",
            "Execute a previously approved conversation LLM tool request through governed capability paths.",
            "llm",
            json!({ "type": "object", "required": ["toolRequestId"], "additionalProperties": true }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &["llm.tool_request"],
        ),
        capability(
            "system.health.check",
            "System Health Check",
            "Create a governed system health check job.",
            "system",
            json!({ "type": "object", "additionalProperties": true }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            true,
            &[],
        ),
        capability(
            "system.health.probe",
            "Probe Appliance Health",
            "Probe daemon health as a task in the operation kernel.",
            "system",
            json!({ "type": "object", "additionalProperties": false }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &[],
        ),
        capability(
            "system.health.record",
            "Record Health Evidence",
            "Record health evidence from a system health check task.",
            "system",
            json!({ "type": "object", "additionalProperties": true }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &["system.health"],
        ),
        capability(
            "scheduler.system.brief.run",
            "Run Due System Brief Schedules",
            "Claim due System Brief schedules and create governed jobs.",
            "system",
            json!({ "type": "object", "additionalProperties": false }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            true,
            &[],
        ),
        capability(
            "brief.system.latest",
            "Read Latest System Brief",
            "Read the latest durable System Brief artifact.",
            "brief",
            json!({ "type": "object", "additionalProperties": false }),
            json!({ "type": "object" }),
            "rust",
            true,
            MCP_EXPORT_POLICY_READ_ONLY,
            false,
            &["brief.system"],
        ),
        capability(
            "brief.system.generate",
            "Generate System Brief",
            "Create a governed System Brief generation job.",
            "brief",
            json!({ "type": "object", "additionalProperties": false }),
            json!({ "type": "object" }),
            "rust",
            true,
            MCP_EXPORT_POLICY_LOCAL_MUTATION,
            true,
            &["brief.system"],
        ),
        capability(
            "brief.scope.validate",
            "Validate Brief Scope",
            "Validate System Brief scope before evidence collection.",
            "brief",
            json!({ "type": "object", "additionalProperties": true }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &[],
        ),
        capability(
            "brief.evidence.collect",
            "Collect Brief Evidence",
            "Collect health, readiness, and schedule evidence for the System Brief.",
            "brief",
            json!({ "type": "object", "additionalProperties": true }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &[],
        ),
        capability(
            "brief.evidence.manifest",
            "Build Evidence Manifest",
            "Build a manifest for brief evidence sources.",
            "brief",
            json!({ "type": "object", "additionalProperties": true }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &[],
        ),
        capability(
            "brief.draft.generate",
            "Generate Brief Draft",
            "Generate deterministic System Brief draft content.",
            "brief",
            json!({ "type": "object", "additionalProperties": true }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &[],
        ),
        capability(
            "brief.claims.validate",
            "Validate Brief Claims",
            "Validate System Brief claims against collected evidence.",
            "brief",
            json!({ "type": "object", "additionalProperties": true }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &[],
        ),
        capability(
            "brief.artifact.save",
            "Save Brief Artifact",
            "Save durable System Brief artifact.",
            "brief",
            json!({ "type": "object", "additionalProperties": true }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &["brief.system"],
        ),
        capability(
            "surface.brief.generate",
            "Generate Surface Brief",
            "Create a deterministic evidence-backed surface brief refresh job.",
            "brief",
            json!({ "type": "object", "additionalProperties": true }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            true,
            &["surface.brief", "artifact.surface_brief"],
        ),
        capability(
            "artifacts.brief.generate",
            "Generate Artifact Brief",
            "Generate brief artifacts for product surfaces from durable evidence.",
            "brief",
            json!({ "type": "object", "additionalProperties": true }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &["artifact.surface_brief"],
        ),
        capability(
            "ethical_persuasion.recommend",
            "Build Ethical Persuasion Recommendation",
            "Build evidence-backed staff-facing persuasion guidance and client-safe language.",
            "brief",
            json!({ "type": "object", "additionalProperties": true }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &["ethical_business_persuasion"],
        ),
        capability(
            "backup.restore_jobs.list",
            "List Backup And Restore Jobs",
            "Read backup and restore job state from SQLite.",
            "backup",
            json!({ "type": "object", "additionalProperties": false }),
            json!({ "type": "object" }),
            "rust",
            true,
            MCP_EXPORT_POLICY_READ_ONLY,
            false,
            &["backup.archive", "restore.safety_record"],
        ),
        capability(
            "backup.create",
            "Create Backup",
            "Create a governed backup job and durable backup archive.",
            "backup",
            json!({ "type": "object", "additionalProperties": false }),
            json!({ "type": "object" }),
            "rust",
            true,
            MCP_EXPORT_POLICY_LOCAL_MUTATION,
            true,
            &["backup.archive"],
        ),
        capability(
            "backup.boundary.check",
            "Check Backup Boundary",
            "Check the appliance data boundary before backup.",
            "backup",
            json!({ "type": "object", "additionalProperties": true }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &[],
        ),
        capability(
            "backup.lock.acquire",
            "Acquire Backup Lock",
            "Acquire the single-appliance backup lock.",
            "backup",
            json!({ "type": "object", "additionalProperties": true }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &[],
        ),
        capability(
            "backup.sqlite.snapshot",
            "Snapshot SQLite",
            "Create a SQLite snapshot for backup.",
            "backup",
            json!({ "type": "object", "additionalProperties": true }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &["backup.archive"],
        ),
        capability(
            "backup.files.scan",
            "Scan Data Files",
            "Scan local appliance files inside the data boundary.",
            "backup",
            json!({ "type": "object", "additionalProperties": true }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &[],
        ),
        capability(
            "backup.archive.write",
            "Write Backup Archive",
            "Write a durable backup archive.",
            "backup",
            json!({ "type": "object", "additionalProperties": true }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &["backup.archive"],
        ),
        capability(
            "backup.manifest.write",
            "Write Backup Manifest",
            "Write a backup manifest with evidence and checksums.",
            "backup",
            json!({ "type": "object", "additionalProperties": true }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &["backup.manifest"],
        ),
        capability(
            "backup.integrity.verify",
            "Verify Backup Integrity",
            "Verify manifest and archive checksums.",
            "backup",
            json!({ "type": "object", "additionalProperties": true }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &[],
        ),
        capability(
            "backup.record",
            "Record Backup",
            "Record backup artifact evidence in SQLite.",
            "backup",
            json!({ "type": "object", "additionalProperties": true }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &["backup.archive"],
        ),
        capability(
            "restore.execute",
            "Execute Restore",
            "Create a governed restore execution job.",
            "restore",
            json!({ "type": "object", "additionalProperties": true }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &["restore.safety_record"],
        ),
        capability(
            "restore.preflight.validate",
            "Validate Restore Preflight",
            "Verify a backup archive and create a non-destructive restore safety record.",
            "restore",
            json!({
                "type": "object",
                "required": ["backupId", "confirmation"],
                "properties": {
                    "backupId": { "type": "string" },
                    "confirmation": { "type": "string" }
                },
                "additionalProperties": false
            }),
            json!({ "type": "object" }),
            "rust",
            true,
            MCP_EXPORT_POLICY_OPERATOR_CONFIRMED,
            false,
            &["restore.safety_record"],
        ),
        capability(
            "restore.request.validate",
            "Validate Restore Request",
            "Validate restore request input.",
            "restore",
            json!({ "type": "object", "additionalProperties": true }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &[],
        ),
        capability(
            "restore.archive.verify",
            "Verify Restore Archive",
            "Verify a backup archive before restore.",
            "restore",
            json!({ "type": "object", "additionalProperties": true }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &[],
        ),
        capability(
            "restore.confirmation.require",
            "Require Restore Confirmation",
            "Require explicit restore confirmation text.",
            "restore",
            json!({ "type": "object", "additionalProperties": true }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &[],
        ),
        capability(
            "restore.safety.backup",
            "Create Restore Safety Backup",
            "Create restore safety evidence before destructive operations.",
            "restore",
            json!({ "type": "object", "additionalProperties": true }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &["restore.safety_record"],
        ),
        capability(
            "restore.lock.acquire",
            "Acquire Restore Lock",
            "Acquire restore lock before live data replacement.",
            "restore",
            json!({ "type": "object", "additionalProperties": true }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &[],
        ),
        capability(
            "restore.sqlite.restore",
            "Restore SQLite",
            "Restore SQLite from a verified backup archive.",
            "restore",
            json!({ "type": "object", "additionalProperties": true }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &[],
        ),
        capability(
            "restore.files.restore",
            "Restore Files",
            "Restore local files from a verified backup archive.",
            "restore",
            json!({ "type": "object", "additionalProperties": true }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &[],
        ),
        capability(
            "restore.state.verify",
            "Verify Restored State",
            "Verify appliance state after restore.",
            "restore",
            json!({ "type": "object", "additionalProperties": true }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &[],
        ),
        capability(
            "system.next.restart",
            "Restart Next.js",
            "Restart the supervised Next.js management process when safe.",
            "system",
            json!({ "type": "object", "additionalProperties": true }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &[],
        ),
        capability(
            "restore.record",
            "Record Restore",
            "Record restore artifact evidence in SQLite.",
            "restore",
            json!({ "type": "object", "additionalProperties": true }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &["restore.record"],
        ),
        capability(
            "diagnostic.logs.list",
            "List Diagnostic Logs",
            "Read recent structured diagnostic logs from local SQLite.",
            "diagnostics",
            json!({ "type": "object", "additionalProperties": true }),
            json!({ "type": "object", "properties": { "logs": { "type": "array" } } }),
            "rust",
            true,
            MCP_EXPORT_POLICY_READ_ONLY,
            false,
            &[],
        ),
        capability(
            "policy.decisions.list",
            "List Policy Decisions",
            "Read bounded recent policy decision audit records for protected local operations.",
            "policy",
            json!({ "type": "object", "additionalProperties": true }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &[],
        ),
        capability(
            "issue.report.list",
            "List Issue Reports",
            "Read locally prepared issue report artifacts.",
            "issue",
            json!({ "type": "object", "additionalProperties": false }),
            json!({ "type": "object", "properties": { "reports": { "type": "array" } } }),
            "rust",
            true,
            MCP_EXPORT_POLICY_READ_ONLY,
            false,
            &["issue.report"],
        ),
        capability(
            "issue.report.prepare",
            "Prepare Issue Report",
            "Create a governed local issue report with diagnostics, evidence, and redaction notes.",
            "issue",
            json!({ "type": "object", "required": ["description"], "additionalProperties": true }),
            json!({ "type": "object" }),
            "rust",
            true,
            MCP_EXPORT_POLICY_LOCAL_MUTATION,
            false,
            &["issue.report"],
        ),
        capability(
            "issue.report.detail",
            "Read Issue Report Detail",
            "Read a local issue report with export, status, and support packet evidence.",
            "issue",
            json!({ "type": "object", "required": ["reportId"], "additionalProperties": false }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &["issue.report"],
        ),
        capability(
            "issue.report.status.update",
            "Update Issue Report Status",
            "Record a local issue report status transition for operator review workflow.",
            "issue",
            json!({ "type": "object", "required": ["reportId", "status"], "additionalProperties": true }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &["issue.report"],
        ),
        capability(
            "issue.report.export",
            "Export Issue Report",
            "Prepare a local markdown export record from a reviewed issue report artifact.",
            "issue",
            json!({ "type": "object", "required": ["reportId"], "additionalProperties": true }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &["issue.report"],
        ),
        capability(
            "support.packets.list",
            "List Support Packets",
            "Read local support packet drafts and approved-local receipts.",
            "support",
            json!({ "type": "object", "additionalProperties": false }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &["support.packet"],
        ),
        capability(
            "support.packets.draft",
            "Draft Support Packet",
            "Prepare a local support packet preview from a redacted issue report without external delivery.",
            "support",
            json!({ "type": "object", "required": ["reportId"], "additionalProperties": true }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &["support.packet"],
        ),
        capability(
            "support.packets.approve",
            "Approve Support Packet Locally",
            "Record explicit owner approval for a support packet without performing external delivery.",
            "support",
            json!({ "type": "object", "required": ["packetId"], "additionalProperties": true }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            true,
            &["support.packet"],
        ),
        capability(
            "support.packet.receipts.list",
            "List Support Packet Receipts",
            "Read local support packet preparation and approval receipts.",
            "support",
            json!({ "type": "object", "required": ["packetId"], "additionalProperties": false }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &["support.packet"],
        ),
        capability(
            "issue.scope.validate",
            "Validate Issue Scope",
            "Validate issue report request scope.",
            "issue",
            json!({ "type": "object", "additionalProperties": true }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &[],
        ),
        capability(
            "issue.narrative.capture",
            "Capture Issue Narrative",
            "Normalize issue report narrative fields.",
            "issue",
            json!({ "type": "object", "additionalProperties": true }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &[],
        ),
        capability(
            "issue.diagnostics.collect",
            "Collect Issue Diagnostics",
            "Collect health, readiness, log, and source diagnostics.",
            "issue",
            json!({ "type": "object", "additionalProperties": true }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &[],
        ),
        capability(
            "issue.events.collect",
            "Collect Issue Events",
            "Collect recent persisted events for issue reports.",
            "issue",
            json!({ "type": "object", "additionalProperties": true }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &[],
        ),
        capability(
            "issue.jobs.collect",
            "Collect Issue Jobs",
            "Collect recent job evidence for issue reports.",
            "issue",
            json!({ "type": "object", "additionalProperties": true }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &[],
        ),
        capability(
            "issue.redactions.apply",
            "Apply Issue Redactions",
            "Apply report redaction policy and record limitations.",
            "issue",
            json!({ "type": "object", "additionalProperties": true }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &[],
        ),
        capability(
            "issue.draft.generate",
            "Generate Issue Draft",
            "Render the local issue report draft.",
            "issue",
            json!({ "type": "object", "additionalProperties": true }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &[],
        ),
        capability(
            "issue.artifact.save",
            "Save Issue Artifact",
            "Save durable issue report artifacts.",
            "issue",
            json!({ "type": "object", "additionalProperties": true }),
            json!({ "type": "object" }),
            "rust",
            false,
            MCP_EXPORT_POLICY_DANGEROUS_NONE,
            false,
            &["issue.report"],
        ),
    ]
}

fn capability(
    id: &str,
    label: &str,
    description: &str,
    family: &str,
    input_schema: Value,
    output_contract: Value,
    execution_target: &str,
    mcp_exported: bool,
    mcp_export_policy: &str,
    scheduler_eligible: bool,
    artifact_kinds: &[&str],
) -> CapabilityDefinition {
    let policy_exported = is_mcp_export_policy_exported(mcp_export_policy);
    debug_assert_eq!(mcp_exported, policy_exported);
    let side_effects = side_effects_for_capability(id, mcp_export_policy);
    CapabilityDefinition {
        id: id.to_string(),
        label: label.to_string(),
        description: description.to_string(),
        family: family.to_string(),
        input_schema,
        output_contract,
        roles_allowed: vec!["owner".to_string(), "system".to_string()],
        execution_target: execution_target.to_string(),
        timeout_seconds: 30,
        retry_policy: json!({ "maxAttempts": 1 }),
        artifact_kinds: artifact_kinds
            .iter()
            .map(|artifact_kind| artifact_kind.to_string())
            .collect(),
        scheduler_eligible,
        prompt_exposure: if policy_exported {
            "system"
        } else {
            "internal"
        }
        .to_string(),
        mcp_export_policy: mcp_export_policy.to_string(),
        side_effects,
        approval_requirement: approval_requirement_for_policy(mcp_export_policy).to_string(),
    }
}

pub(crate) fn is_mcp_export_policy_exported(policy: &str) -> bool {
    matches!(
        policy,
        MCP_EXPORT_POLICY_READ_ONLY
            | MCP_EXPORT_POLICY_LOCAL_MUTATION
            | MCP_EXPORT_POLICY_OPERATOR_CONFIRMED
    )
}

fn side_effects_for_capability(id: &str, mcp_export_policy: &str) -> Vec<String> {
    let side_effects = match id {
        "brief.system.generate" => &["creates_job", "writes_sqlite", "writes_brief_artifact"][..],
        "surface.brief.generate" => &[
            "creates_job",
            "writes_sqlite",
            "writes_surface_brief_artifact",
        ][..],
        "hosted_trials.capacity.inspect" => &[][..],
        "hosted_trials.reset_ready.validate" => &[
            "writes_sqlite",
            "records_owner_decision",
            "marks_reset_ready_without_wipe",
        ][..],
        "offer_builder.write" => &[
            "writes_sqlite",
            "validates_offer_publication",
            "records_offer_event",
        ][..],
        "backup.create" => &["creates_job", "writes_sqlite", "writes_backup_archive"][..],
        "restore.preflight.validate" => &[
            "creates_job",
            "writes_sqlite",
            "writes_restore_safety_record",
        ][..],
        "restore.execute" => &["not_mcp_exported", "may_replace_live_state"][..],
        "issue.report.prepare" => &[
            "creates_job",
            "writes_sqlite",
            "writes_issue_report_artifact",
        ][..],
        _ if mcp_export_policy == MCP_EXPORT_POLICY_READ_ONLY => &[][..],
        _ => &["not_mcp_exported", "internal_kernel_effects"][..],
    };
    side_effects
        .iter()
        .map(|effect| effect.to_string())
        .collect()
}

fn approval_requirement_for_policy(policy: &str) -> &str {
    match policy {
        MCP_EXPORT_POLICY_READ_ONLY => "none",
        MCP_EXPORT_POLICY_LOCAL_MUTATION => "local_access_required",
        MCP_EXPORT_POLICY_OPERATOR_CONFIRMED => "operator_confirmation_required",
        MCP_EXPORT_POLICY_DANGEROUS_NONE => "not_exported",
        _ => "not_exported",
    }
}
